INSERT INTO public.lemonsquad_field_maps (form_key, form_hash, mapping_json, sample_fields_json)
VALUES (
  'inspection_report',
  'v7-2026-07',
  jsonb_build_object(
    'sections', jsonb_build_array('Upload Images','Upload Video','Vehicle Info','Warranty Info','Engine','Road Test','Findings','Edit Images','Review'),
    'dashboard', '{
      "kpi_selectors": {
        "in_progress": ".dashboard-kpi[data-label=\"In Prog.\"] .value",
        "complete": ".dashboard-kpi[data-label=\"Complete\"] .value",
        "late": ".dashboard-kpi[data-label=\"Late\"] .value",
        "refunded": ".dashboard-kpi[data-label=\"Refunded\"] .value",
        "avg_time": ".dashboard-kpi[data-label=\"Avg. Time\"] .value",
        "fastest_turnaround": ".dashboard-kpi[data-label=\"Fastest Turnaround\"]",
        "slowest_turnaround": ".dashboard-kpi[data-label=\"Slowest Turnaround\"] .value"
      },
      "category_tabs": ["Motorcycle","Standard","Classic","Exotic","RV","Commercial","Mechanical","LPB Installation","Intoxalock Service","Other"],
      "job_card": {
        "container": ".job-card, [data-order-id]",
        "order_number": ".job-card .order-number, [data-order-id]",
        "inspection_name": ".job-card .inspection-name",
        "vehicle_ymm": ".job-card .vehicle-title",
        "city": ".job-card .address-city",
        "shop_name": ".job-card .shop-name",
        "shop_contact": ".job-card .shop-contact",
        "street_address": ".job-card .street-address",
        "address_state_zip": ".job-card .address-line-2",
        "phone": ".job-card a[href^=\"tel:\"]",
        "tech_fee": ".job-card .tech-fee",
        "received_at": ".job-card .received-at",
        "accepted_at": ".job-card .accepted-at",
        "current_eta": ".job-card .current-eta",
        "due_by": ".job-card .due-by",
        "notes": ".job-card .notes-block",
        "enter_job_button": ".job-card a:has-text(\"Enter Job\")",
        "print_form_button": ".job-card a:has-text(\"Print Form\")",
        "request_eta_button": ".job-card a:has-text(\"Request ETA Change\")"
      }
    }'::jsonb,
    'job_header', '{
      "job_number": "h1:has-text(\"Job #\")",
      "vehicle_ymm": ".job-header .vehicle-title",
      "vin": ".job-header .vin, [data-field=\"vin\"]",
      "inspection_name": ".job-header .inspection-name",
      "reason_for_inspection_block": ".job-header .reason-for-inspection",
      "general_notes_block": ".job-header .general-notes",
      "customer_name": ".job-header .customer-name",
      "customer_email": ".job-header a[href^=\"mailto:\"]",
      "customer_phone": ".job-header a[href^=\"tel:\"]",
      "repair_shop_name": ".job-header .repair-shop-name",
      "claim_adjuster_name": ".job-header .claim-adjuster-name",
      "claim_adjuster_email": ".job-header .claim-adjuster-email"
    }'::jsonb,
    'fields', '{
      "upload_images.dropzone":       {"section":"Upload Images","selector":"input[type=\"file\"][accept*=\"image\"]","type":"file","per_photo":true,"source":"photo.binary"},
      "upload_video.main_dropzone":   {"section":"Upload Video","selector":"input[type=\"file\"][accept*=\"video\"]","type":"file","constraints":{"formats":["mp4"],"max_mb":390,"resolution":"720p-480p","length_sec_min":30,"length_sec_max":45},"source":"inspection.video.main"},
      "upload_video.evo":             {"section":"Upload Video","selector":"#evo-video-upload input[type=\"file\"]","type":"file","source":"inspection.video.evo"},
      "vehicle.year":                 {"section":"Vehicle Info","selector":"input[name=\"year\"]","type":"text","source":"vehicle.year","readonly":true},
      "vehicle.make":                 {"section":"Vehicle Info","selector":"input[name=\"make\"]","type":"text","source":"vehicle.make","readonly":true},
      "vehicle.model":                {"section":"Vehicle Info","selector":"input[name=\"model\"]","type":"text","source":"vehicle.model","readonly":true},
      "vehicle.vin":                  {"section":"Vehicle Info","selector":"input[name=\"vin\"]","type":"text","source":"vehicle.vin","required":true},
      "vehicle.stock_no":             {"section":"Vehicle Info","selector":"input[name=\"stock_no\"]","type":"text","source":"vehicle.stock_no"},
      "vehicle.mileage":              {"section":"Vehicle Info","selector":"input[name=\"mileage\"]","type":"text","unit":"mi","source":"vehicle.mileage"},
      "vehicle.engine_size_l":        {"section":"Vehicle Info","selector":"input[name=\"engine_size\"]","type":"text","unit":"L","source":"vehicle.engine_size_l"},
      "vehicle.transmission":         {"section":"Vehicle Info","selector":"select[name=\"transmission\"]","type":"select","source":"vehicle.transmission"},
      "vehicle.drive_type":           {"section":"Vehicle Info","selector":"select[name=\"drive_type\"]","type":"select","source":"vehicle.drive_type"},
      "vehicle.tire_size":            {"section":"Vehicle Info","selector":"input[name=\"tire_size\"]","type":"text","source":"vehicle.tire_size"},
      "vehicle.stock_tires":          {"section":"Vehicle Info","selector":"input[name=\"stock_tires\"]","type":"radio","options":["Yes","No"],"source":"vehicle.stock_tires"},
      "vehicle.trans_model":          {"section":"Vehicle Info","selector":"input[name=\"trans_model\"]","type":"text","source":"vehicle.trans_model"},
      "fluids.evidence_of_metal":     {"section":"Vehicle Info","selector":"input[name=\"fluids_evidence_metal\"]","type":"radio","options":["Yes","No","N/A"],"source":"inspection.fluids.evidence_of_metal"},
      "fluids.evidence_intermixing":  {"section":"Vehicle Info","selector":"input[name=\"fluids_evidence_intermixing\"]","type":"radio","options":["Yes","No","N/A"],"source":"inspection.fluids.evidence_of_intermixing"},
      "fluids.coolant_level":         {"section":"Vehicle Info","selector":"select[name=\"coolant_level\"]","type":"select","source":"inspection.fluids.coolant.level"},
      "fluids.coolant_condition":     {"section":"Vehicle Info","selector":"select[name=\"coolant_condition\"]","type":"select","source":"inspection.fluids.coolant.condition"},
      "fluids.coolant_leaking":       {"section":"Vehicle Info","selector":"input[name=\"coolant_leaking\"]","type":"radio","options":["Yes","No","N/A"],"source":"inspection.fluids.coolant.leaking"},
      "fluids.transmission_level":    {"section":"Vehicle Info","selector":"select[name=\"transmission_level\"]","type":"select","source":"inspection.fluids.transmission.level"},
      "fluids.transmission_condition":{"section":"Vehicle Info","selector":"select[name=\"transmission_condition\"]","type":"select","source":"inspection.fluids.transmission.condition"},
      "fluids.transmission_leaking":  {"section":"Vehicle Info","selector":"input[name=\"transmission_leaking\"]","type":"radio","options":["Yes","No","N/A"],"source":"inspection.fluids.transmission.leaking"},
      "fluids.oil_level":             {"section":"Vehicle Info","selector":"select[name=\"oil_level\"]","type":"select","source":"inspection.fluids.oil.level"},
      "fluids.oil_condition":         {"section":"Vehicle Info","selector":"select[name=\"oil_condition\"]","type":"select","source":"inspection.fluids.oil.condition"},
      "fluids.oil_leaking":           {"section":"Vehicle Info","selector":"input[name=\"oil_leaking\"]","type":"radio","options":["Yes","No","N/A"],"source":"inspection.fluids.oil.leaking"},
      "fluids.transfer_case_level":   {"section":"Vehicle Info","selector":"select[name=\"transfer_case_level\"]","type":"select","source":"inspection.fluids.transfer_case.level"},
      "fluids.transfer_case_condition":{"section":"Vehicle Info","selector":"select[name=\"transfer_case_condition\"]","type":"select","source":"inspection.fluids.transfer_case.condition"},
      "fluids.transfer_case_leaking": {"section":"Vehicle Info","selector":"input[name=\"transfer_case_leaking\"]","type":"radio","options":["Yes","No","N/A"],"source":"inspection.fluids.transfer_case.leaking"},
      "fluids.power_steering_level":  {"section":"Vehicle Info","selector":"select[name=\"power_steering_level\"]","type":"select","source":"inspection.fluids.power_steering.level"},
      "fluids.power_steering_condition":{"section":"Vehicle Info","selector":"select[name=\"power_steering_condition\"]","type":"select","source":"inspection.fluids.power_steering.condition"},
      "fluids.power_steering_leaking":{"section":"Vehicle Info","selector":"input[name=\"power_steering_leaking\"]","type":"radio","options":["Yes","No","N/A"],"source":"inspection.fluids.power_steering.leaking"},
      "fluids.front_diff_level":      {"section":"Vehicle Info","selector":"select[name=\"front_differential_level\"]","type":"select","source":"inspection.fluids.front_differential.level"},
      "fluids.front_diff_condition":  {"section":"Vehicle Info","selector":"select[name=\"front_differential_condition\"]","type":"select","source":"inspection.fluids.front_differential.condition"},
      "fluids.front_diff_leaking":    {"section":"Vehicle Info","selector":"input[name=\"front_differential_leaking\"]","type":"radio","options":["Yes","No","N/A"],"source":"inspection.fluids.front_differential.leaking"},
      "fluids.rear_diff_level":       {"section":"Vehicle Info","selector":"select[name=\"rear_differential_level\"]","type":"select","source":"inspection.fluids.rear_differential.level"},
      "fluids.rear_diff_condition":   {"section":"Vehicle Info","selector":"select[name=\"rear_differential_condition\"]","type":"select","source":"inspection.fluids.rear_differential.condition"},
      "fluids.rear_diff_leaking":     {"section":"Vehicle Info","selector":"input[name=\"rear_differential_leaking\"]","type":"radio","options":["Yes","No","N/A"],"source":"inspection.fluids.rear_differential.leaking"},
      "fluids.brake_level":           {"section":"Vehicle Info","selector":"select[name=\"brake_fluid_level\"]","type":"select","source":"inspection.fluids.brake.level"},
      "fluids.brake_condition":       {"section":"Vehicle Info","selector":"select[name=\"brake_fluid_condition\"]","type":"select","source":"inspection.fluids.brake.condition"},
      "fluids.brake_leaking":         {"section":"Vehicle Info","selector":"input[name=\"brake_fluid_leaking\"]","type":"radio","options":["Yes","No","N/A"],"source":"inspection.fluids.brake.leaking"},
      "condition.vehicle_condition":  {"section":"Vehicle Info","selector":"select[name=\"vehicle_condition\"]","type":"select","source":"inspection.condition.overall"},
      "condition.signs_of_abuse":     {"section":"Vehicle Info","selector":"input[name=\"signs_of_abuse\"]","type":"radio","options":["Yes","No"],"source":"inspection.condition.abuse"},
      "condition.signs_of_collision": {"section":"Vehicle Info","selector":"input[name=\"signs_of_collision\"]","type":"radio","options":["Yes","No"],"source":"inspection.condition.collision"},
      "condition.signs_of_modifications":{"section":"Vehicle Info","selector":"input[name=\"signs_of_modifications\"]","type":"radio","options":["Yes","No"],"source":"inspection.condition.modifications"},
      "condition.signs_of_commercial":{"section":"Vehicle Info","selector":"input[name=\"signs_of_commercial_use\"]","type":"radio","options":["Yes","No"],"source":"inspection.condition.commercial_use"},
      "condition.trailer_hitch":      {"section":"Vehicle Info","selector":"input[name=\"trailer_hitch\"]","type":"radio","options":["Yes","No"],"source":"inspection.condition.trailer_hitch"},
      "warranty.repair_order":        {"section":"Warranty Info","selector":"input[name=\"repair_order\"]","type":"text","source":"inspection.warranty.repair_order"},
      "warranty.repair_order_date":   {"section":"Warranty Info","selector":"input[name=\"repair_order_date\"]","type":"date","source":"inspection.warranty.repair_order_date"},
      "warranty.towed_to_shop":       {"section":"Warranty Info","selector":"input[name=\"towed_to_shop\"]","type":"radio","options":["Yes","No"],"source":"inspection.warranty.towed_to_shop"},
      "warranty.labor_rate":          {"section":"Warranty Info","selector":"input[name=\"labor_rate\"]","type":"text","unit":"$/hr","source":"inspection.warranty.labor_rate"},
      "warranty.previous_repair_history":{"section":"Warranty Info","selector":"input[name=\"previous_repair_history\"]","type":"radio","options":["Yes","No"],"source":"inspection.warranty.previous_repair_history"},
      "engine.belts_hoses":           {"section":"Engine","selector":"input[name=\"belts_hoses\"]","type":"radio","options":["Good","Bad","N/A"],"source":"inspection.engine.belts_hoses"},
      "engine.varnish_sludge":        {"section":"Engine","selector":"select[name=\"varnish_sludge\"]","type":"select","source":"inspection.engine.varnish_sludge"},
      "engine.radiator_condition":    {"section":"Engine","selector":"select[name=\"radiator_condition\"]","type":"select","source":"inspection.engine.radiator_condition"},
      "engine.evidence_of_overheating":{"section":"Engine","selector":"input[name=\"evidence_of_overheating\"]","type":"radio","options":["Yes","No","N/A"],"source":"inspection.engine.evidence_of_overheating"},
      "engine.air_filter_condition":  {"section":"Engine","selector":"select[name=\"air_filter_condition\"]","type":"select","source":"inspection.engine.air_filter_condition"},
      "road_test.performed":          {"section":"Road Test","selector":"input[name=\"road_test_performed\"]","type":"radio","options":["Yes","No"],"source":"inspection.road_test.completed"},
      "findings.verbal_required":     {"section":"Findings","selector":"input[name=\"verbal_required\"]","type":"radio","options":["Yes","No"],"source":"inspection.verbal_required"},
      "findings.person_spoken_to":    {"section":"Findings","selector":"input[name=\"person_spoken_to\"]","type":"text","source":"inspection.verbal.contact_name"},
      "findings.time_of_call":        {"section":"Findings","selector":"input[name=\"time_of_call\"]","type":"text","placeholder":"e.g. 2:30 PM","source":"inspection.verbal.time"},
      "findings.reason_for_inspection":{"section":"Findings","selector":"textarea[name=\"reason_for_inspection\"]","type":"textarea","source":"inspection_request.customer_complaint","readonly":true},
      "findings.state_of_assembly":   {"section":"Findings","selector":"textarea[name=\"state_of_assembly\"]","type":"textarea","source":"inspection.state_of_assembly"},
      "findings.suspected_cause":     {"section":"Findings","selector":"textarea[name=\"suspected_cause_of_failure\"]","type":"textarea","source":"inspection.suspected_cause"},
      "findings.concern_reproduced":  {"section":"Findings","selector":"input[name=\"concern_reproduced\"]","type":"radio","options":["Yes","No"],"source":"inspection.concern_reproduced"},
      "findings.inspector_observations":{"section":"Findings","selector":"textarea[name=\"inspector_observations\"]","type":"textarea","source":"inspection.notes"},
      "images.caption":               {"section":"Edit Images","selector":"input[name^=\"image_caption_\"]","type":"text","source":"photo.caption","per_photo":true},
      "images.annotation":            {"section":"Edit Images","selector":"select[name^=\"image_annotation_\"]","type":"select","options":["Cover Photo","Front of Repair Facility","OBD2 Image","VIN Image","Odometer Reading","Undercarriage"],"source":"photo.annotation","per_photo":true}
    }'::jsonb,
    'required_annotations', jsonb_build_array('Cover Photo','Front of Repair Facility','OBD2 Image','VIN Image','Odometer Reading','Undercarriage'),
    'nav', jsonb_build_object('next_selector','button:has-text("Next")','save_selector','button:has-text("Save!!")','save_quit_selector','button:has-text("Save & Quit")','submit_selector','button:has-text("Submit Job")'),
    'submission_mode_default','draft_only'
  ),
  jsonb_build_object('captured_from','user screenshots IMG_0360..IMG_0374','captured_at','2026-07-08','includes',jsonb_build_array('dashboard','job_header','upload_images','upload_video','vehicle_info','fluids','condition_of_vehicle','warranty_info','engine','road_test','findings','edit_images'))
)
ON CONFLICT (form_key, form_hash) DO UPDATE
  SET mapping_json = EXCLUDED.mapping_json,
      sample_fields_json = EXCLUDED.sample_fields_json,
      updated_at = now();